"""horos public Python API (R2: the business-logic layer).

Everything the Web API and CLI expose routes through functions defined in this
package; each public function is registered in the capability manifest (E9-T1).
"""

from horos.api.annotate import (
    AnnotationProgress,
    AnnotationSetView,
    ClaimResult,
    QueueItem,
    annotation_progress,
    claim_image,
    get_annotations,
    image_file_path,
    image_queue,
    release_claim,
    save_annotations,
)
from horos.api.autolabel import (
    AssistResult,
    PromptSpec,
    assist_image,
    pending_summary,
    review_pending,
    start_autolabel,
)
from horos.api.dataset import (
    DeleteImagesSummary,
    ImportSummary,
    ValidationFixResult,
    convert_dataset,
    dataset_stats,
    delete_images,
    export_dataset,
    fix_validation_issues,
    import_dataset,
    import_zip,
    list_images,
    resplit,
    validate_project,
)
from horos.api.evaluate import (
    ClassEval,
    EvalReport,
    get_eval_report,
    infer_image,
    start_evaluation,
)
from horos.api.hparams import DerivedValue, HyperparameterPlan
from horos.api.install import InstallPlan, MLReadiness, check_ml_ready, plan_install
from horos.api.jobs import JobStatus, cancel_job, job_status
from horos.api.labels import add_category, delete_category, update_category
from horos.api.manifest import Capability, get_capability, list_capabilities
from horos.api.media import (
    MediaFrame,
    MediaItem,
    delete_media,
    get_media,
    list_media,
    start_media_inference,
)
from horos.api.project import create_project, open_project
from horos.api.system import (
    DoctorReport,
    PlatformCapabilities,
    doctor_report,
    ensure_supported,
    list_models,
    platform_capabilities,
)
from horos.api.train import (
    RunRecord,
    TrainRunConfig,
    TrainStatus,
    delete_run,
    derive_hyperparameters,
    list_runs,
    start_training,
    stop_training,
    training_status,
    update_queued_run,
)
from horos.api.verdict import Finding, RunVerdict, run_verdict

__all__ = [
    "AnnotationProgress",
    "AnnotationSetView",
    "AssistResult",
    "Capability",
    "ClaimResult",
    "ClassEval",
    "DeleteImagesSummary",
    "DerivedValue",
    "DoctorReport",
    "EvalReport",
    "Finding",
    "HyperparameterPlan",
    "ImportSummary",
    "InstallPlan",
    "JobStatus",
    "MLReadiness",
    "PlatformCapabilities",
    "PromptSpec",
    "QueueItem",
    "RunRecord",
    "RunVerdict",
    "TrainRunConfig",
    "TrainStatus",
    "ValidationFixResult",
    "add_category",
    "annotation_progress",
    "assist_image",
    "cancel_job",
    "check_ml_ready",
    "claim_image",
    "convert_dataset",
    "create_project",
    "dataset_stats",
    "delete_category",
    "delete_images",
    "delete_media",
    "delete_run",
    "derive_hyperparameters",
    "doctor_report",
    "ensure_supported",
    "export_dataset",
    "fix_validation_issues",
    "get_annotations",
    "get_capability",
    "get_eval_report",
    "image_file_path",
    "image_queue",
    "import_dataset",
    "import_zip",
    "infer_image",
    "job_status",
    "list_capabilities",
    "list_images",
    "list_models",
    "MediaFrame",
    "MediaItem",
    "list_media",
    "list_runs",
    "open_project",
    "pending_summary",
    "plan_install",
    "platform_capabilities",
    "release_claim",
    "resplit",
    "review_pending",
    "get_media",
    "run_verdict",
    "save_annotations",
    "start_autolabel",
    "start_evaluation",
    "start_media_inference",
    "start_training",
    "stop_training",
    "training_status",
    "update_category",
    "update_queued_run",
    "validate_project",
]
